# Student Performance Analysis

This project analyzes student performance using statistical methods.

Dataset Description:

- Dataset contains 100 students
- Includes marks, study hours, and sleep hours
- Data is randomly generated for analysis

Import Libraries

In [1]:
import numpy as np
import pandas as pd

In [2]:
np.random.seed(42)

data = {
    "Marks": np.random.randint(40, 100, 100),
    "Study_Hours": np.random.randint(1, 10, 100),
    "Sleep_Hours": np.random.randint(4, 10, 100)
}

df = pd.DataFrame(data)

df.head()

   Marks  Study_Hours  Sleep_Hours
0     78            7            5
1     91            9            7
2     68            8            9
3     54            5            8
4     82            2            4

In [3]:
df.shape

(100, 3)

In [4]:
df.describe()

            Marks  Study_Hours  Sleep_Hours
count  100.000000   100.000000    100.00000
mean    69.580000     5.220000      6.28000
std     18.031499     2.830498      1.71199
min     41.000000     1.000000      4.00000
25%     54.000000     3.000000      5.00000
50%     68.000000     5.000000      6.00000
75%     86.000000     8.000000      7.00000
max     99.000000     9.000000      9.00000

In [5]:
df.to_csv("../data/student_data.csv", index=False)